// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHuks8zISz0pSadGefFcm8Oy6oh-qr-eQ',
    appId: '1:375077613453:web:1cf275cf830d66c94357c4',
    messagingSenderId: '375077613453',
    projectId: 'health-app-svadhruthi',
    authDomain: 'health-app-svadhruthi.firebaseapp.com',
    storageBucket: 'health-app-svadhruthi.appspot.com',
    measurementId: 'G-00Y1YK25F2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmc5KXkoGFK11eaQlOiS5U66ecIEJAkhc',
    appId: '1:375077613453:android:a9532ffba3136fcc4357c4',
    messagingSenderId: '375077613453',
    projectId: 'health-app-svadhruthi',
    storageBucket: 'health-app-svadhruthi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa2FqDSpei_JBPjszzkRXLN_A8GKC3l04',
    appId: '1:375077613453:ios:e9355a3d04a59ca94357c4',
    messagingSenderId: '375077613453',
    projectId: 'health-app-svadhruthi',
    storageBucket: 'health-app-svadhruthi.appspot.com',
    iosClientId: '375077613453-p49q4mt5hb5bramb0g8uhbot8b27r0o3.apps.googleusercontent.com',
    iosBundleId: 'com.example.sva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa2FqDSpei_JBPjszzkRXLN_A8GKC3l04',
    appId: '1:375077613453:ios:b33acaba78981d264357c4',
    messagingSenderId: '375077613453',
    projectId: 'health-app-svadhruthi',
    storageBucket: 'health-app-svadhruthi.appspot.com',
    iosClientId: '375077613453-leierne000s2dh0botjjh7hrlf4st03p.apps.googleusercontent.com',
    iosBundleId: 'com.example.sva.RunnerTests',
  );
}
